### PR TITLE
add linuxbrew support

### PR DESCRIPTION
**Pull request by glensc**
http://linuxbrew.sh/

don't forget to add "linux" tag to github project once merged ;)

todo:
- [x] test
- [x] `plist_options` certainly not needed. but doesn't interfere, can stay
- [ ] update install docs in main minio repo

### CODE REVIEW

**Comment by glensc** [comment]
`mc` seems working
```
[/opt/linuxbrew/Homebrew/Library/Taps/minio/homebrew-stable (patch-1)★] ➔ brew install minio/stable/mc
==> Installing mc from minio/stable
==> Downloading https://dl.minio.io/client/mc/release/linux-amd64/mc
######################################################################## 100,0%
🍺- /opt/linuxbrew/Homebrew/Cellar/mc/20171014005116Z_1:d3 fiaes, 7.7MB, built in 20 seconds
[/opt/linuxbrew/Homebrew/Library/Taps/minio/homebrew-stable (patch-1)★] ➔ which mc
/opt/linuxbrew/Homebrew/bin/mc
[/opt/linuxbrew/Homebrew/Library/Taps/minio/homebrew-stable (patch-1)★] ➔ mc --version
Incorrect Usage. flag provided but not defined: -version
```

**Comment by glensc** [comment]
`minio` install also works

```
[/opt/linuxbrew/Homebrew/Library/Taps/minio/homebrew-stable (patch-1)★] ➔ brew install minio/stable/minio
==> Installing minio from minio/stable
==> Downloading https://dl.minio.io/server/minio/release/linux-amd64/minio
#######################################                                   54,6%
######################################################################## 100,0%
🍺  /opt/linuxbrew/Homebrew/Cellar/minio/20171122195546Z_1: 3 files, 20.9MB, built in 1 minute 1 second
[/opt/linuxbrew/Homebrew/Library/Taps/minio/homebrew-stable (patch-1)★] ➔
[/opt/linuxbrew/Homebrew/Library/Taps/minio/homebrew-stable (patch-1)★] ➔ which minio
/opt/linuxbrew/Homebrew/bin/minio
[/opt/linuxbrew/Homebrew/Library/Taps/minio/homebrew-stable (patch-1)★] ➔ minio --version
Incorrect Usage. flag provided but not defined: -version
```

**Comment by harshavardhana** [comment]
We are not planning to add Linux support for brew just yet @glensc - but thanks for sending the PR though.

**Comment by glensc** [comment]
leaving as is is bad as well. brew install succeeds, but installs osx binary, which isn't executable.

how about not having it official but just be there unofficially?

other choices would be to make it osx specific, i.e define urls only for `OS.mac?`

**Comment by glensc** [comment]
added note about linuxbrew to readme: 9813f3f, may need rewording

**Comment by harshavardhana** [comment]
> leaving as is is bad as well. brew install succeeds, but installs osx binary, which isn't executable.

We should add a `if conditional` for that rather than adding Linux IMO for now.

**Comment by glensc** [comment]
updated to raise error on linuxbrew

```
[/opt/linuxbrew/Homebrew/Library/Taps/minio/homebrew-stable (patch-1)★] ➔ brew install minio/stable/mc
Error: No Linux support
[/opt/linuxbrew/Homebrew/Library/Taps/minio/homebrew-stable (patch-1)★] ➔
```

**Pull request merged**
